Remove unnecessary code for activation twentynineteen theme
After we updated the oldest supported WP and PHP versions, we don't need this theme anymore.
When I checked recent builds, I notice we are getting:

Error: The 'twentynineteen' theme could not be found.

So it already works for some time without the theme being activated.
[MAILPOET-5925]