Fix imports that are causing errors in the premium build
For some unknown reason using the absolute paths in the files changed in
this commit is causing the error below in the premium build. To fix it,
this commit changes the code to use relative paths. I did not
investigate why this error was happening in the first place.

The error started happening when
https://github.com/mailpoet/mailpoet/pull/5213/ was merged.

```
> tsc --noEmit

../mailpoet/assets/js/src/segments/dynamic/dynamic-segments-filters/automation-options.ts:2:29 - error TS2307: Cannot find module 'segments/dynamic/dynamic-segments-filters/sort-filters' or its corresponding type declarations.

2 import { sortFilters } from 'segments/dynamic/dynamic-segments-filters/sort-filters';
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../mailpoet/assets/js/src/segments/dynamic/dynamic-segments-filters/email-options.ts:2:29 - error TS2307: Cannot find module 'segments/dynamic/dynamic-segments-filters/sort-filters' or its corresponding type declarations.

2 import { sortFilters } from 'segments/dynamic/dynamic-segments-filters/sort-filters';
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../mailpoet/assets/js/src/segments/dynamic/dynamic-segments-filters/subscriber-options.ts:2:29 - error TS2307: Cannot find module 'segments/dynamic/dynamic-segments-filters/sort-filters' or its corresponding type declarations.

2 import { sortFilters } from 'segments/dynamic/dynamic-segments-filters/sort-filters';
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../mailpoet/assets/js/src/segments/dynamic/dynamic-segments-filters/woocommerce-options.ts:2:29 - error TS2307: Cannot find module 'segments/dynamic/dynamic-segments-filters/sort-filters.ts' or its corresponding type declarations.

2 import { sortFilters } from 'segments/dynamic/dynamic-segments-filters/sort-filters.ts';
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Found 4 errors in 4 files.
```

https://app.circleci.com/pipelines/github/mailpoet/mailpoet-premium/2862/workflows/b1fa2ad0-fc50-40df-b278-c6ca709e6ce0/jobs/20223

[MAILPOET-5666]