Update Tracy to version 2.9.7 to get rid of PHP 8.2 warnings
We were running Tracy 2.9.1 and this version was generating warnings
when running PHP 8.2. Example:

```
ErrorException: Creation of dynamic property Tracy\DefaultBarPanel::$time is deprecated in phar:///var/www/html/wp-content/plugins/mailpoet/tools/vendor/tracy.phar/Tracy/Bar/panels/info.tab.phtml:2
```

[MAILPOET-5265]